name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'

    - name: Create Clean Project & Build APK
      run: |
        flutter create . --org com.ps4.installer --project-name ps4_installer --platforms android --overwrite
        flutter build apk --release --no-tree-shake-icons

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PS4-Installer-APK
        path: build/app/outputs/flutter-apk/app-release.apk
